install.packages("dplyr")
install.packages("quanteda")
install.packages("dplyr")
install.packages("stringr")
install.packages("tidytext")
install.packages("ggplot2")
install.packages("quanteda.textplots")
install.packages("quanteda.textstats")
install.packages("udpipe")
install.packages("ggplot2")
install.packages("textplot")
install.packages("flextable")
install.packages("cfa")
install.packages("tm")

